### ISSUE TITLE
[14기 오다민]git-github-2 과제

### ISSUE THREAD

**Issue by ODamDam** [EwhaKing/king14-assignment#49]
아직 정규 세션 참여는 두 번 밖에 안 했지만, 많은 걸 배울 수 있었습니다.
많이 배우고, 공부해서 멋진 KING 부원이 되도록 노력하겠습니다!!

**Comment by KangSYeon** [comment]
많이 배울 수 있었다니 기쁘네요!
다음 세션도 알찬 시간이 될 수 있도록 노력하겠습니다~
노력하신 만큼 좋은 성과 얻어가실 수 있을 거예요 파이팅입니다!
