### ISSUE TITLE
[13기 표은서] git-github-2 과제

### ISSUE THREAD

**Issue by eses9688** [EwhaKing/king14-assignment#55]
깃허브를 아직 많이 사용해본 적이 없었는데, 이번 세션에서 여러 가지를 배우게 되어서 유익한 시간이었습니다! 협업할 때 많은 도움이 될 것 같아요 감사합니다 :>

**Comment by SYEON10** [comment]
과제1 PR 연결해주세요!
세션 공부하느라 수고하셨습니다.
