### ISSUE TITLE
[14기 오승연] git-github-2 과제 

### ISSUE THREAD

**Issue by Oec8cek** [EwhaKing/king14-assignment#63]
이번 깃허브 세션을 통해 깃허브 명령어에 대해서 다시 한번 훑고 지나갈 수 있어서 좋았고 디스코드로 화면공유를 해서 보다 수업을 들을 때 좋았던 것 같습니다 감사합니다!

**Comment by SYEON10** [comment]
PR 연결해주세요! 감사합니당~
